### ISSUE TITLE
Support AVIF format

### ISSUE THREAD

**Issue by sycured** [imager-io/imager#10]
It'll be good to have AVIF format as possible output using a library like https://crates.io/crates/ravif

**Comment by rudolphos** [comment]
It seems to be abandonware now.

**Comment by mxdpeep** [comment]
> It seems to be abandonware now.

**https://en.wikipedia.org/wiki/AVIF** not abandoned

Apple Platforms - iOS 16, iPadOS 16, [macOS Ventura](https://en.wikipedia.org/wiki/MacOS_Ventura) have AVIF image support. You can directly store and view AVIF photos in the Photos and Files app, etc.

**Comment by sycured** [comment]
@mxdpeep I think it's more about https://github.com/imager-io/imager

edit: I'll take a look if I've time to fork and implement AVIF + update dependencies
