### ISSUE TITLE
Update install.md?

### ISSUE THREAD

**Issue by vpoulailleau** [imager-io/imager#7]
Thanks for imager! It's great!

BTW, I followed instructions in https://github.com/imager-io/imager/blob/master/docs/imager/install.md

It mentions imager v0.3.3, but it seems to be an auto release of v0.3.4.

Should the documentation be updated?

**Comment by colbyn** [comment]
Yeah ideally it should be updated, but it should be fine. Keeping everything in sync takes a lot of effort (and I'm currently overloaded with schoolwork), and in this case it shouldn't matter (also in general newer versions should always be preferable to older releases).

Also thanks for the remark. 🙂

**Comment by PoorPocketsMcNewHold** [comment]
Note that it could be solved, by naming all the next releases with generic name without their version numbers.

https://docs.github.com/en/enterprise/2.22/user/github/administering-a-repository/linking-to-releases

So, by renaming them respectfully \`[imager-apple.tar.gz](https://github.com/imager-io/imager/releases/download/auto-release%2Fimager%2F0.3.4/imager-v0.3.4-apple.tar.gz)\` and \`[imager-linux.tar.gz](https://github.com/imager-io/imager/releases/download/auto-release%2Fimager%2F0.3.4/imager-v0.3.4-apple.tar.gz)\` you could link the latest releases directly via : `/owner/name/releases/latest/download/asset-name.zip`

`https://github.com/imager-io/imager/releases/latest/download/imager-apple.tar.gz` 

`https://github.com/imager-io/imager/releases/latest/download/imager-linux.tar.gz`
